=head1 NAME Sigma6

CIJoe is a Real American Hero ... Sigma6 continues the battle against Pyth^WCobra

=head1 SYNOPSIS

    > cat sigma6.ini
    [Build::Manager]
    [Template::Tiny]
    [JSON]

    [Queue::Mmap]
    file        = /tmp/sigma6/queue.dat
    size        = 10
    record_size = 20
    mode        = 0666

    [Smoker::Simple]
    workspace      = /tmp/sigma6/test
    smoker_command = bin/smoker.pl --config etc/sigma6.ini

    [Git]
    note_command  = notes --ref=sigma6-test add -fm

    [Github]

    [Dzil]
    deps_command  = cpanm -L perl5 --installdeps Makefile.PL
    build_command = prove -I perl5/lib/perl5 -lwrv t/ 

    > plackup app.psgi

=head1 DESCRIPTION

Sigma6 is a Continuous Integration application originally based upon
CIJoe. Additionally the tests are coming along actually, and you're reading all of the
documentation there is. 

=head1 THANKS

Portions of Sigam6's development (like the entire Plugin System) were 
funded by SocialFlow. Special thanks go out to them.

